---
- hosts: all
  vars:
    locale: en_US.utf8
    timezone: Asia/Manila

  tasks:
  - name: Install Nginx
    shell: apt-get install -y nginx 
    become: true

  - name: Start Nginx
    shell: /etc/init.d/nginx start
   
  



